name: oookki
display_name: "Oookki thème principal"
version: 1.0.0
author:
  name: "Liberty Media SAS"
  url: "https://oookki.com"

meta:
  compatibility:
    from: 8.1.0
    to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column

assets:
# If you're using this theme as child and you want to load
# the parent theme assets, uncomment this line.
#  use_parent_assets: true

# The following lines are showing how to load assets in your page
# Uncomment and change value to start loading css or js files
#  css:
#  all:
#    - id: custom-lib-style
#    path: assets/css/custom-lib.css
#  product:
#    - id: product-style
#    path: assets/css/product.css
#    media: all
#    priority: 200
#  js:
#  cart:
#    - id: cat-extra-lib
#    path: assets/js/cart-lib.js

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_enable:
      - ps_linklist
  hooks:
    custom_hooks:
      - name: displayMainMenu
        title: displayMainMenu
        description: Affiche le menu principal
    modules_to_hook:
      displayMainMenu:
        - ps_mainmenu
      displayAfterBodyOpeningTag:
        - blockreassurance
      displayNavFullWidth:
        - blockreassurance
      displayAdminCustomers:
        - blockwishlist
      displayCustomerAccount:
        - blockwishlist
        - psgdpr
      displayMyAccountBlock:
        - blockwishlist
      displayNav1:
        - ps_contactinfo
      displayNav2:
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
        - ps_searchbar
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_banner
        - ps_customtext
        - ps_specials
        - ps_newproducts
        - ps_bestsellers
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
        - blockreassurance
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
        - blockwishlist
      displayFooterAfter:
        - blockreassurance
      displayFooterProduct:
        - productcomments
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displayContactLeftColumn:
        - ps_contactinfo
      displayContactRightColumn:
        - ps_contactinfo
      displayContactContent:
        - contactform
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - productcomments
      displayProductListReviews:
        - productcomments
      displayReassurance:
        - blockreassurance
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayProductActions:
        - blockwishlist

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [ products ]
    small_default:
      width: 125
      height: 125
      scope: [ products, categories, manufacturers, suppliers ]
    medium_default:
      width: 600
      height: 600
      scope: [ products, manufacturers, suppliers ]
    home_default:
      width: 600
      height: 600
      scope: [ products ]
    large_default:
      width: 1024
      height: 1024
      scope: [ products, manufacturers, suppliers ]
    category_default:
      width: 300
      height: 300
      scope: [ categories ]
    stores_default:
      width: 300
      height: 300
      scope: [ stores ]
  new_password_policy_feature: true

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column